name: "Hibur Mono"
designer: "Behailu Berento"
license: "OFL"
category: "MONOSPACE"
date_added: "2026-03-08"
fonts {
  name: "Hibur Mono"
  style: "normal"
  weight: 400
  filename: "HiburMono-Regular.ttf"
  post_script_name: "HiburMono-Regular"
  full_name: "Hibur Mono Regular"
  copyright: "Copyright 2025-2026 The Hibur Mono Font Project Authors (https://github.com/typehabesha/HiburMono). Noto glyphs are Copyright 2015 Google LLC. All Rights Reserved."
}
subsets: "adlam"
subsets: "cherokee"
subsets: "ethiopic"
subsets: "greek"
subsets: "greek-ext"
subsets: "latin"
subsets: "latin-ext"
subsets: "math"
subsets: "menu"
subsets: "tifinagh"
subsets: "yi"
soruce {
  repository_url: "https://github.com/typehabesha/HiburMono"
  commit: "62012e80578aff6fb8c41d052eb745a85b1685f3"
}
primary_script: "Ethi"
minisite_url: "https://github.com/typehabesha/HiburMono"
stroke: "SANS SERIF"
